// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV64eekfqL8VXDwP7ctAkSKRc7ws8tR3E',
    appId: '1:187518301820:web:5e6438ac4733084635fbf9',
    messagingSenderId: '187518301820',
    projectId: 'internshiphub-4d40a',
    authDomain: 'internshiphub-4d40a.firebaseapp.com',
    storageBucket: 'internshiphub-4d40a.firebasestorage.app',
    measurementId: 'G-4BC1VKZY6D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoTRh6V2nD6ner3it1yw3dRk3Yqchuqzc',
    appId: '1:187518301820:android:95a85115cf85783135fbf9',
    messagingSenderId: '187518301820',
    projectId: 'internshiphub-4d40a',
    storageBucket: 'internshiphub-4d40a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDShq9kpkOpW3dcx-F6XDHT_cemWMRAYNk',
    appId: '1:187518301820:ios:aa9c2b36a6b957fe35fbf9',
    messagingSenderId: '187518301820',
    projectId: 'internshiphub-4d40a',
    storageBucket: 'internshiphub-4d40a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDShq9kpkOpW3dcx-F6XDHT_cemWMRAYNk',
    appId: '1:187518301820:ios:aa9c2b36a6b957fe35fbf9',
    messagingSenderId: '187518301820',
    projectId: 'internshiphub-4d40a',
    storageBucket: 'internshiphub-4d40a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAV64eekfqL8VXDwP7ctAkSKRc7ws8tR3E',
    appId: '1:187518301820:web:128ecaa17193a50235fbf9',
    messagingSenderId: '187518301820',
    projectId: 'internshiphub-4d40a',
    authDomain: 'internshiphub-4d40a.firebaseapp.com',
    storageBucket: 'internshiphub-4d40a.firebasestorage.app',
    measurementId: 'G-CGXKXLFYM4',
  );
}
